trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: RunTests
  displayName: 'Run Tests'
  steps:
- task: CmdLine@2
  inputs:
    script: |
      cd  $(System.DefaultWorkingDirectory)
      "C:\Program Files\Parasoft\SOAtest & Virtualize\2023.1\soatestcli.exe" -data "$(System.DefaultWorkingDirectory)\workspace" -resource "\TestAssets\test" -config "soatest.user://Example Configuration" -environment "Environment1"

  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
