trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: RunTests
  displayName: 'Run Tests'
  steps:
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: |
        **/rep*.xml
        **/rep*.sarif
        **/coverage.xml
      testRunTitle: 'Test Results'

  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
